name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Touch local properties
      run: touch local.properties
    - name: Add Api Key
      run: echo "apiKey=\"\"" >> local.properties
    - name: Ktint format
      run: ./gradlew ktlintFormat --stacktrace
    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v3.0.0
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
